### ISSUE TITLE
FEATURE - align README with source package readme

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_stripe#20]
we don't have the following sections/variables in the transform package readme. they are technically scoped to the source package, but users of the transform package may likely not go there 
- https://github.com/fivetran/dbt_stripe_source#pivoting-out-metadata-properties
- https://github.com/fivetran/dbt_stripe_source#including-sub-invoice-line-items
- https://github.com/fivetran/dbt_stripe_source#running-on-live-vs-test-customers

**Comment by fivetran-reneeli** [comment]
See https://github.com/fivetran/dbt_stripe/pull/21
