### ISSUE TITLE
FEATURE - Add More Context to the `using_invoice_line_sub_filter` variable

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_stripe#26]
**Are you a Fivetran customer?** 

Fivetran created FR

**Is your feature request related to a problem? Please describe.**
 
The `using_invoice_line_sub_filter` can be somewhat confusing to understand for a first time user of this package. As highlighted by a customer within [dbt Slack](https://getdbt.slack.com/archives/C01D1R2JLLA/p1643657793265829?thread_ts=1643656636.010939&cid=C01D1R2JLLA) we should add more context within our README to help users understand _why_ this is included and _when_ to leverage the variable.

**Describe the solution you'd like**
 
The README has more context as to what the variable is and why it is included, and also when to use it. The slack thread linked above adds some good info that we should add.

**Describe alternatives you've considered**
 
The current README state.

**Comment by fivetran-reneeli** [comment]
Closing this issue out as we've added more [context](https://github.com/fivetran/dbt_stripe/blob/main/README.md#including-sub-invoice-line-items) in our README.
