### ISSUE TITLE
[Bug] Issue with stripe source on dbt run

### ISSUE THREAD

**Issue by shaon-chowdhury** [fivetran/dbt_stripe#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When I try to `dbt run` for the first time, I get the following error because the stripe subscription table does not exist.

```
Database Error in model stg_stripe__subscription_tmp (models/tmp/stg_stripe__subscription_tmp.sql)
relation "stripe.subscription" does not exist
LINE 7: from "db"."stripe"."subscription"
             ^
 compiled SQL at target/run/stripe_source/models/tmp/stg_stripe__subscription_tmp.sql
Done. PASS=32 WARN=0 ERROR=1 SKIP=4 TOTAL=37
```

In my database, Fivetran does not export a table named `subscription` but instead the following tables.

```
subscription_history
subscription_discount
subscription_item
subscription_tax_rate
```

Is there an easy fix for this?

### Expected behavior

This should either look for a table with another name or build properly.

### dbt Project configurations

Using the latest dbt version as of 28th March and have only installed the stripe package.

### Package versions

```
packages:
  - package: fivetran/stripe
    version: [">=0.6.0", "<0.7.0"]
```

### What database are you using dbt with?

postgres

### dbt Version

dbt installed version: 1.0.4

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @shaon-chowdhury thanks so much for opening this issue 👋 

If you do not have the `subscriptions` source table, then you will still be able to leverage this dbt package by [disabling the subscription models](https://github.com/fivetran/dbt_stripe#disabling-models). To do so, you can add the following to your `dbt_project.yml`

```yml
vars:
    using_subscriptions:   False
```

Let me know if you have any other questions!

**Comment by shaon-chowdhury** [comment]
@fivetran-joemarkiewicz thanks for your help! Still confused as to why Fivetran does not export the subscription table but I'll reach out to their support

**Comment by fivetran-joemarkiewicz** [comment]
Of course, happy to help! 

When I have seen tables like this not being synced in the past it is usually because there isn't any data available from the endpoint. However, if you have the other subscriptions tables then I would wonder why the base table isn't being synced either. Reaching out to support would be the best next step.

Thanks!

**Comment by rhinck** [comment]
@fivetran-joemarkiewicz 

Looking at the ERD [here](https://docs.google.com/presentation/d/1zyxgbaOjgBt3NsY0OfsiGsWDIefcBc-R1lHWlMltCYU/edit#slide=id.gd0264d4694_14_1), it looks like the `subscription` table is now `subscription_history` if I'm not mistaken. 

I've been running into the error as @shaon-chowdhury. Is there a way using this package that I can remap `subscription` to `subscription_history`? 

I just started using dbt today so I apologize if I'm missing something obvious.
