### ISSUE TITLE
Your package relies on older versions of dbt-utils, which means our project is stuck on an older version 

### ISSUE THREAD

**Issue by rbrooks** [fivetran/dbt_stripe#49]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Your package relies on older versions of dbt-utils, which means ours is stuck on an older version.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Closing this as PR #48 has been merged and released. The package is now using the latest version of dbt-utils
