### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by fivetran-kristin** [fivetran/dbt_stripe#5]
https://github.com/dataform-co/dataform-fivetran-stripe/commit/1ac7ba3bdd176678170596cc77e5c73d857a29bd

https://github.com/dataform-co/dataform-fivetran-stripe/commit/b400c22dddc6bbcfab61b6d533d63d71b8bd3a13

**Comment by fivetran-joemarkiewicz** [comment]
Addressed in PR #8
