### ISSUE TITLE
Add table rename at the end of each refresh 

### ISSUE THREAD

**Issue by nbenezri** [fivetran/dbt_stripe#57]
Some tables take a long time to refresh, like:

```
09:12:05  119 of 175 START table model cdp_stripe.stripe__invoice_line_items ............. [RUN]
09:15:08  119 of 175 OK created table model cdp_stripe.stripe__invoice_line_items ........ [SELECT in 183.45s]
```

During this time - the table is not available to query in prod.
One way to resolve this is to run in the end:

```
DROP TABLE IF EXISTS cdp_stripe.stripe__invoice_line_items_prod;
ALTER TALBE cdp_stripe.stripe__invoice_line_items rename to cdp_stripe.stripe__invoice_line_items_prod;
```

Is there such a way to do it when each table is ready?

**Comment by fivetran-reneeli** [comment]
Hi @nbenezri thanks for opening this issue! 

Just to confirm I understand, are you saying that after the refreshed table gets created again, you're unable to query from it? But by renaming the table then you can? I'm having trouble understanding why it's unable to be queried in the first place. Or, can you query in dev, just not in prod?

**Comment by nbenezri** [comment]
When the refreshes going on it is unavailable. In the above example, during 09:12:05 - 09:15:08.

**Comment by fivetran-reneeli** [comment]
Hi @nbenezri sorry for the delay! I understand the issue you're experiencing, though this is the way dbt works as is it runs a create or replace statement. I think the issue may be better resolved looking at how your environment is set up. I would suggest working with your engineering team to make sure your dashboards are still available during table refreshes-- there should be some kind of best practices for when prod goes offline temporarily.

**Comment by nbenezri** [comment]
Yeah, I will rename the tables after each refresh.
I thought there might be something simpler.


*Thanks,*
*Nir Ben Ezri*
*DBA Team Lead*
*DistroKid*
*https://distrokid.com* <https://distrokid.com/>
