### ISSUE TITLE
update required dbt version to allow v0.19.0

### ISSUE THREAD

**Issue by MarkMacArdle** [fivetran/dbt_stripe#6]
dbt v0.19.0 was released on Jan 27th but this package has the below line in it's `dbt_project.yml`

```
require-dbt-version: [">=0.18.0", "<0.19.0"]
```

Be great if this could be updated to allow use of latest version of dbt.

The Stripe source package would also need to be updated.

**Comment by fivetran-kristin** [comment]
@MarkMacArdle thanks for surfacing this issue! I just pushed changes to update this. 

I've released version 0.2.1, which will have these changes.  Once this version is published to the hub (generally happens within 24 hours), you will be able to upgrade on your side.

Thanks!
