### ISSUE TITLE
[Bug] Line Item Enhanced - Refunds not included

### ISSUE THREAD

**Issue by rick1290** [fivetran/dbt_stripe#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Noticing that no refunds are captured in this table

### Expected behavior

Refunds should display on the invoice or item id

### Possible solution

Something to do with the transaction id.... i think using the charge id allows you to map it correctly. Trying to play around with it.

### dbt Project configurations

Default

### Package versions

Current Version

### What database are you using dbt with?

snowflake

### How are you running this dbt package?

dbt Cloud™

### dbt Version

Current

### Additional Context

I just think there is an issue with one of the joins. Take a look at charge_id 

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
@rick1290 thanks for opening this issue and providing insight into the refunds not displaying as expected. 

When looking at the [ERD](https://docs.google.com/presentation/d/1zyxgbaOjgBt3NsY0OfsiGsWDIefcBc-R1lHWlMltCYU/edit#slide=id.g25ac7999fa1_0_0) it looks like there is a possible connection via balance_transaction_id. However, to your point as well it looks like it could also map via the charge_id.
![image](https://github.com/user-attachments/assets/f9558bdb-6389-4126-9c72-cc651e048d25)

Have you been able to play around with this on your end? Do you see the charge_id mapping the refunds appropriately? I'll also call out that we perform this same join in the [stripe__balance_transactions](https://github.com/fivetran/dbt_stripe/blob/7cfdfc5ea37ee32e1be2df5601229b4096b6f6d3/models/stripe__balance_transactions.sql#L282-L284) model.

**Comment by rick1290** [comment]
@fivetran-joemarkiewicz Charge Id indeed works..... and applies the refund to the invoice level. Balance transaction does not work or map correctly. 

So I guess in this enhanced table - the REFUND would only apply at the header level it seems.

**Comment by fivetran-joemarkiewicz** [comment]
@rick1290 I wanted to let you know that I've been looking into this and agree there likely needs to be a change to properly account for refunds. However, I've seen some conflicting results when swapping the join with data on our end 🤔.

I'll continue to investigate and will share here once I have found a viable solution to this issue that will work for all use cases. Thanks!

**Comment by fivetran-avinash** [comment]
Hi @rick1290! I made some changes to our `stripe_line_item_enhanced` model [in a branch you can test out.](https://github.com/fivetran/dbt_stripe/tree/bugfix/updated-line-item-enhanced)

Since charges and refunds are both types of balance transactions, but a refund is tied to the charge, and this model is primarily bringing in balance transaction charges, I included an additional join to bring in balance transaction refunds so that they could exist at the same level. 

I then summed the fee amounts from both refunds and charges, and changed the type to account for a charge that also has a refund. 

Let me know your thoughts or if there is anything that is still not quite working for your use case!

**Comment by fivetran-avinash** [comment]
Hi @rick1290 , just circling back here, were you able to test this new version of the `stripe__line_item_enhanced` model? Just want to make sure it works for your purposes. Let us know if you have any questions!

**Comment by fivetran-avinash** [comment]
Hi @rick1290 ! We are planning to bring this task into our current sprint and work on this potential solution shortly. I just wanted to make sure that this proposed scoping made sense or if there are any nuances we might have missed. 

If we don't hear back, we will keep you in the loop regarding development on this issue.

**Comment by fivetran-avinash** [comment]
Hi @rick1290 , these updates are now live [on the latest version of stripe on the dbt hub.](https://hub.getdbt.com/fivetran/stripe/latest/) Closing this ticket, but let us know if you have any questions, thoughts, or concerns, for refunds now properly being reflected.
